#! /bin/sh

# dunst
killall -q dunst
dunst &

# mpDris2
mpDris_pid=$(pgrep -f mpDris2)
kill -9 $mpDris_pid
mpDris2 &

# redshift
redshift_pid=$(pgrep redshift)
if [ -z $redshift_pid ]; then
	redshift -c ~/.config/redshift/redshift.conf &
fi

# polkit
lxpolkit_pid=$(pgrep lxpolkit)
if [ -z $lxpolkit_pid ]; then
	/usr/lib/lxpolkit/lxpolkit &
fi

# greenclip
killall -q -9 greenclip
greenclip daemon &

# locker
killall -q light-locker
light-locker --lock-on-lid --lock-on-suspend --class Bspwm &

# megasync
#killall mega-cmd-server
#mega-cmd-server &

# keepassxc
killall keepassxc
keepassxc &

# powermanager
killall mate-power-manager
mate-power-manager &

#xpad
#killall -q xpad
#xpad &

exit 1
