#! /bin/sh

# dunst
killall -q dunst
dunst &

# mpDris2
mpDris_pid=$(pgrep -f mpDris2)
kill -9 $mpDris_pid
mpDris2 &

# redshift
killall -q redshift
redshift -x
redshift -c ~/.config/redshift/redshift.conf &

# polkit
lxpolkit_pid=$(pgrep lxpolkit)
if [ -z lxpolkit_pid ]; then
	/usr/lib/lxpolkit/lxpolkit &
fi

# greenclip
killall -q -9 greenclip
greenclip daemon &

# locker
killall -q light-locker
light-locker --lock-on-lid --lock-on-suspend --class Bspwm &

#xpad
#killall -q xpad
#xpad &

exit 1
