#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# General config
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_radius		12
bspc config border_width         0
bspc config window_gap          15

bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# App rule
bspc rule -a Polybar layer=below locked=on
bspc rule -a Gimp-2.10 desktop='^8' state=tiling follow=on
bspc rule -a Blueman-manager state=floating
bspc rule -a Blueman-services state=floating
bspc rule -a URxvt state=floating center=true
bspc rule -a smplayer state=floating
bspc rule -a Bluetooth-sendto state=floating center=true
bspc rule -a XAVA state=floating border=off locked=on sticky=on layer=below manage=off
bspc rule -a Arandr state=floating
bspc rule -a File-roller state=floating
bspc rule -a octopi state=floating
bspc rule -a octopi-cachecleaner state=floating
bspc rule -a Gnome-disks state=floating
bspc rule -a Viewnior state=floating follow=on center=true
bspc rule -a Gpick state=floating
bspc rule -a L3afpad state=floating
bspc rule -a Pavucontrol state=floating rectangle=745x424
bspc rule -a Catfish state=floating
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a Yad state=floating
bspc rule -a System-config-printer.py state=floating center=true rectangle=720x500+0+0
bspc rule -a Galculator state=floating
bspc rule -a hp-toolbox state=floating
bspc rule -a xpad state=floating border=off locked=on sticky=on layer=below manage=off
bspc rule -a xdman-Main state=floating
bspc rule -a scrcpy state=floating
bspc rule -a Nm-connection-editor state=floating center=true
bspc rule -a Light-locker-settings.py state=floating center=true
bspc rule -a Wihotspot-gui state=floating center=true
bspc rule -a Trebleshot state=floating center=true
bspc rule -a Cpupower-gui state=floating center=true
bspc rule -a jetbrains-studio:jetbrains-studio:win0 state=floating center=true
bspc rule -a Seahorse state=floating
bspc rule -a balena-etcher-electron state=floating
bspc rule -a Java:java:Dbeaver state=floating center=true
bspc rule -a Magnus state=floating
bspc rule -a Weston\ Compositor state=floating
bspc rule -a Caffeine state=floating
bspc rule -a Xfce4-power-manager-settings state=floating center=true
bspc rule -a Brave-browser:crx_nkbihfbeogaeaoehlefnkodbefgpgknn state=floating

# bspwm color
#bspc config active_border_color "#AD8C34"
#bspc config normal_border_color "#AD8C34"
#bspc config focused_border_color "#FFD86E"

# Wallpaper
$HOME/.local/bin/change-desktop-background

# Polybar
$HOME/.config/polybar/launch

# Urxvtd
killall -q urxvtd
urxvtd -q -o -f &

# Picom
killall -q picom
picom --config ~/.config/picom/picom.conf &

# Autostart
$HOME/.config/bspwm/autostart > /dev/null 2>&1

#notify complete
notify-send "Welcome $USER !"
