#!/usr/bin/env bash

# export DISPLAY=":0"
# export XAUTHORITY="$HOME/.Xauthority"
# export XDG_RUNTIME_DIR="/run/user/1000"
export DEFAULT_NETWORK_INTERFACE=$(ip addr | awk '/state UP/ {print $2; exit}' | sed 's/.$//')

# Variable
source $HOME/.r3dmoon_var

# Terminate already running bar instances
killall -q polybar

# If all your bars have ipc enabled, you can also use
#polybar-msg cmd quit 

# Launch bar1 and bar2
echo "---" | tee -a /tmp/polybar1.log /tmp/polybar2.log
polybar mybar >>/tmp/polybar1.log 2>&1 & disown

echo "Bars launched..."
